name: Nova Deriv Copy Trading Platform

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m venv venv 
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_URI=${{ secrets.DB_URI }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

    # Add other steps as needed for your build process
